apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector: { matchLabels: { app: admin } }
  template:
    metadata: { labels: { app: admin } }
    spec:
      containers:
        - name: admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [{ containerPort: 5173 }]
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  selector: { app: admin }
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP