name: Release Images
on:
  push:
    tags:
      - "v*"
jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm -C apps/backend build
      - run: pnpm -C apps/admin build

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fanno-backend:${{ github.ref_name }} -f apps/backend/Dockerfile apps/backend
      - name: Build admin
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fanno-admin:${{ github.ref_name }} -f apps/admin/Dockerfile apps/admin

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/fanno-backend:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/fanno-admin:${{ github.ref_name }}